version: '3'

services:

  redis:
    image: redis
    ports:
      - '6377:6379'

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
    - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5431:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - app
      - redis

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    depends_on:
      - app
      - redis

volumes:
  pg_data:
